#@ load("/values.star", "values")
#@ load("/values.star", "labels")

---
apiVersion: v1
kind: Namespace
metadata:
  name: #@ values.namespace
  labels: #@ labels()


---
apiVersion: v1
kind: Secret
metadata:
  labels:
    component: velero
  name: cloud-credentials
  namespace: velero
type: Opaque
data:
  cloud: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkPUFLSUFZTERITDNYUDZBSE1XUFg1CmF3c19zZWNyZXRfYWNjZXNzX2tleT1qL3BxRXFDa2FvVm5LTXVRUkp6M2h6WTdvU0RDaE0xdE9IZVZQMFpBCgoK
