- apiVersion: velero.io/v1
  kind: BackupStorageLocation
  metadata:
    creationTimestamp: null
    labels:
      component: velero
    name: default
    namespace: velero
  spec:
    config:
      region: us-west-2
    default: true
    objectStorage:
      bucket: c-aws-velero-bucket
    provider: aws