#@ load("/values.star", "values")
#@ load("@ytt:overlay", "overlay")

#@ def non_empty(node):
#@   result = {}
#@   for key in node:
#@     if not node[key] == "" and not node[key] == None:
#@       result[key] = node[key]
#@     end
#@   end
#@   return result
#@ end
