#@ load("@ytt:overlay", "overlay")
#@ load("/values.star", "values")
#@ load("/values.star", "resource")
#@ load("/values.star", "secret_name")

#@overlay/match by=overlay.subset({"kind": "DaemonSet", "metadata":{"name":"restic"}})
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    #@overlay/match missing_ok=True
    kapp.k14s.io/update-strategy: "skip"

#@overlay/match by=overlay.subset(resource("ClusterRoleBinding", values.rbac.name))
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    #@overlay/match missing_ok=True
    kapp.k14s.io/update-strategy: "skip"

#@overlay/match by=overlay.subset({"kind": "CustomResourceDefinition", "spec":{"group":"velero.io"}}),expects=[11]
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    #@overlay/match missing_ok=True
    kapp.k14s.io/update-strategy: "skip"

#@ if values.credential.useDefaultSecret:
#@overlay/match by=overlay.subset(resource("Secret", "cloud-credentials"))
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    #@overlay/match missing_ok=True
    kapp.k14s.io/update-strategy: "skip"
#@ end

#@overlay/match by=overlay.subset(resource("Namespace", values.namespace))
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    #@overlay/match missing_ok=True
    kapp.k14s.io/update-strategy: "skip"
