#@ load("/values.star", "values")
#@ load("@ytt:overlay", "overlay")
#@ load("/values.star", "labels")
#@ load("/helpers.lib.yaml", "non_empty")

#@ if values.rbac.create and values.rbac.clusterAdministrator:

#@overlay/match by=overlay.subset({"kind": "ClusterRoleBinding"}),expects=[1]
---
#@overlay/match-child-defaults missing_ok=True
metadata:
  name: #@ values.rbac.name
roleRef:
  name: #@ values.rbac.roleRefName
subjects:
- kind: ServiceAccount
  #@ non_empty(values.serviceAccount)

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-reader
rules:
- apiGroups: #@ values.rbac.clusterRoleAPIGroups
  #!
  #! at the HTTP level, the name of the resource for accessing Secret
  #! objects is "secrets"
  resources: ["secrets"]
  verbs: #@ values.rbac.clusterRoleverbs
#@ end

#@ if values.rbac.create:
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: velero-server
rules:
  - apiGroups:
      - velero.io
    verbs:
      - "*"
    resources:
      - "*"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels: #@ labels()
  name: velero-server
subjects:
  - kind: ServiceAccount
    name: #@ values.serviceAccount.name
roleRef:
  kind: Role
  name: #@ values.rbac.roleRefName
  apiGroup: rbac.authorization.k8s.io
#@ end
