#@ load("/values.star", "values")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind": "Secret", "metadata": {"name": "cloud-credentials"}})
#@overlay/replace
apiVersion: v1
kind: Secret
metadata:
  name:
type: Opaque
data:
