#@ load("/values.star", "values")
#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:json", "json")
#@ load("/values.star", "labels")

#@overlay/match by=overlay.subset({"kind": "Secret", "metadata": {"name": "cloud-credentials"}})
#@overlay/replace
apiVersion: v1
kind: Secret
metadata:
  labels: #@ labels()
  namespace: #@ values.namespace
type: Opaque
data:
    #! username: #@ base64.encode(values.akoOperator.config.avi_username)
    #! password: #@ base64.encode(values.akoOperator.config.avi_password)

#! #@overlay/match by=overlay.subset({"kind": "Secret", "metadata": {"name": "avi-controller-ca"}})
#! ---
#! #@overlay/replace
#! apiVersion: v1
#! kind: Secret
#! metadata:
#!     name: #@ values.akoOperator.config.avi_ca_name
#!     namespace: #@ values.akoOperator.namespace
#! type: Opaque
#! data:
#!     certificateAuthorityData: #@ values.akoOperator.config.avi_ca_data_b64