#@ load("/values.star", "values")
#@ load("@ytt:overlay", "overlay")
#@ load("/values.star", "velero_app")
#@ load("/values.star", "labels")

#@overlay/match by=overlay.subset({"kind": "Namespace"}),expects=[1]
---
metadata:
  name: #@ values.namespace

#! #@overlay/match by=overlay.subset({"kind": "ConfigMap"}),expects=[1]
#! #@overlay/match-child-defaults missing_ok=True
#! ---
#! metadata:
#!   labels: #@ labels()
#!   namespace: #@ values.namespace

#@overlay/match by=overlay.subset({"kind": "ServiceAccount"}),expects=[1]
#@overlay/match-child-defaults missing_ok=True
---
metadata:
  labels: #@ labels()
  namespace: #@ values.namespace

#@overlay/match by=overlay.subset({"kind": "Role"}),expects=[1]
---
#@overlay/match-child-defaults missing_ok=True
metadata:
  labels: #@ labels()
  name: #@ values.namespace

#@overlay/match by=overlay.subset({"kind": "RoleBinding"}),expects=[1]
---
#@overlay/match-child-defaults missing_ok=True
metadata:
  labels: #@ labels()
  name: #@ values.namespace

#@overlay/match by=overlay.subset({"kind": "ClusterRole"}),expects=[1]
---
#@overlay/match-child-defaults missing_ok=True
metadata:
  labels: #@ labels()
  namespace: #@ values.namespace

#@overlay/match by=overlay.subset({"kind": "ClusterRoleBinding"}),expects=[1]
---
#@overlay/match-child-defaults missing_ok=True
metadata:
  labels: #@ labels()
  namespace: #@ values.namespace

#@overlay/match by=overlay.subset({"kind": "Deployment"}),expects=[1]
---
#@overlay/match-child-defaults missing_ok=True
metadata:
  labels: #@ labels()
  namespace: #@ values.namespace

#@overlay/match by=overlay.subset({"kind": "DaemonSet"}),expects="0+"
---
#@overlay/match-child-defaults missing_ok=True
metadata:
  labels: #@ labels()
  namespace: #@ values.namespace

#@overlay/match by=overlay.subset({"kind": "Secret"}),expects="1+"
---
#@overlay/match-child-defaults missing_ok=True
metadata:
  labels: #@ labels()
  namespace: #@ values.namespace

#@ if/end values.backupStorageLocation.backupsEnabled:
#@overlay/match by=overlay.subset({"kind": "BackupStorageLocation"}),expects="1+"
---
#@overlay/match-child-defaults missing_ok=True
metadata:
  labels: #@ labels()
  namespace: #@ values.namespace
