apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: velero.community.tanzu.vmware.com.1.6.3
  namespace: velero
spec:
  refName: velero.community.tanzu.vmware.com
  version: 1.6.3
  releaseNotes: "velero 1.6.3 https://github.com/vmware-tanzu/velero/releases/tag/v1.6.3"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/velero@sha256:072c3431c131c3e8512549d93e670eb883b26f9ae6212920b1d45ace6afdc41b
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
