apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: velero.community.tanzu.vmware.com.1.6.3
  namespace: velero
spec:
  refName: velero.community.tanzu.vmware.com
  version: 1.6.3
  releaseNotes: "velero 1.6.3 https://github.com/vmware-tanzu/velero/releases/tag/v1.6.3"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/velero@sha256:af56da2abe320d62c8a8542187b3b7db245de9495f3bd9d3b914ee899c2c6997
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
