apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: cert-manager.community.tanzu.vmware.com.1.3.3
spec:
  refName: cert-manager.community.tanzu.vmware.com
  version: 1.3.3
  releasedAt: 2021-08-06T12:31:21Z
  releaseNotes: "cert-manager 1.3.3 https://github.com/jetstack/cert-manager/releases/tag/v1.3.3"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/cert-manager@sha256:c087c02ac3957486baeb91f9e0713a2d672dd7532c739ed836e9795e4160aeb6
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
  capacityRequirementsDescription: "Varies significantly based on number of Certificate objects"
  valuesSchema:
    openAPIv3:
      title: cert-manager.community.tanzu.vmware.com.1.3.3 values schema
      examples:
        - namespace: tanzu-certificates
      properties:
        namespace:
          type: string
          description: The namespace in which to deploy cert-manager.
          default: tanzu-certificates
