name: Check lint

on:
  pull_request:
    types:
      - assigned
      - opened
      - synchronize
      - reopened
    paths:
      - "**.go"
      - "hack/check-lint.sh"

jobs:
  checklint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: "1.16"
        id: go

      - name: Config credentials
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global url."https://git:$GITHUB_TOKEN@github.com".insteadOf "https://github.com"

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.38.0
          args: --timeout=10m -v
