name: Check build

on:
  pull_request:
    types:
      - assigned
      - opened
      - synchronize
      - reopened

jobs:
#  checkbuild:
#    name: Check Build
#    runs-on: ubuntu-latest
#    steps:
#      - name: Set up Go 1.x
#        uses: actions/setup-go@v2
#        with:
#          go-version: "1.16"
#        id: go
#
#      - name: Config credentials
#        env:
#          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
#        run: |
#          git config --global url."https://git:$GH_ACCESS_TOKEN@github.com".insteadOf "https://github.com"
#
#      - name: Check out code into the Go module directory
#        uses: actions/checkout@v1
#
#      - name: Get dependencies
#        run: |
#          go get -v -t -d ./...
#
#      - name: Build
#        run: make build
#  e2e:
#    name: Check Build
#    runs-on: ubuntu-latest
#      - name: Get cert-manager-e2e
#        uses: docker://projects-stg.registry.vmware.com/tkg/cert-manager-e2e-test/e2e-test:v1.1.0-dirty.2
#
#      - name: Run cert-manager-e2e
#        run: |
#          docker run -v /var/run/docker.sock:/var/run/docker.sock --privileged --network host projects-stg.registry.vmware.com/tkg/cert-manager-e2e-test/e2e-test:v1.1.0-dirty.2
  cert-manager-image:
    name: Build cert-manager e2e test image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the cert-manager e2e Docker image
        run: |
          cd addons/packages/cert-manager/test/e2e
          docker build -t cert-manager-e2e-test --build-arg CERT_MANAGER_VERSION=v1.1.0 .
  cert-manager-e2e:
    name: Run cert-manager e2e tests
    needs: cert-manager-image
    runs-on: ubuntu-latest
    container:
      image: cert-manager-e2e-test
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      options: --cpus 2 --privileged --name cert-manager-e2e-test
    steps:
      - name: run tests
        run: |
          cd /workspace
          /workspace/devel/ci-run-e2e.sh --ginkgo.focus="Certificates|CA Certificate|Self Signed Certificate|RBAC" --ginkgo.skip=ACME